//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Android_2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDiaChi
    {
        public string TenDuong { get; set; }
        public string SoNha { get; set; }
        public int IDND { get; set; }
        public int IDdiaChi { get; set; }
    
        public virtual DiaChiND DiaChiND { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
