//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Android_2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTiet_SP
    {
        public string MoTa { get; set; }
        public int GiaBan { get; set; }
        public int GiaMua { get; set; }
        public int SoLuong { get; set; }
        public int IDSP { get; set; }
        public int IDKichThuoc { get; set; }
    
        public virtual KichThuoc KichThuoc { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
