//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Android_2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaChiND
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiaChiND()
        {
            this.ChiTietDiaChis = new HashSet<ChiTietDiaChi>();
        }
    
        public int IDdiaChi { get; set; }
        public string TenDiaChi { get; set; }
        public int IDThanhPho { get; set; }
        public int IDtinh { get; set; }
        public Nullable<int> IDQuan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDiaChi> ChiTietDiaChis { get; set; }
        public virtual Quan Quan { get; set; }
        public virtual ThanhPho ThanhPho { get; set; }
        public virtual TinhThanh TinhThanh { get; set; }
    }
}
